[package]
name = "plutus"
version = "1.6.1"
edition = "2021"
publish = false
license = "Apache-2.0"

[dependencies]
hex = { workspace = true }
minicbor = { workspace = true }
num-bigint = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
num-traits = { workspace = true }

[dev-dependencies]
hex = { workspace = true }
num-traits = { workspace = true }
