[package]
name = "ariadne-simulator"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
version.workspace = true
license = "Apache-2.0"
description = "Executable tool for simulating committee selection using the Ariadne algorithm"

[dependencies]
selection = { workspace = true, default-features = true }
serde = { workspace = true }
serde_json = { workspace = true }
clap = { workspace = true }
rand_chacha = { workspace = true }
rand = { workspace = true }
log = { workspace = true }
env_logger = { workspace = true }
itertools = { workspace = true }

[lints]
workspace = true
