[package]
name = "partner-chains-plutus-data"
version = "1.5.1"
edition = "2021"
description = "Parsing and serialization of Plutus data schemas used by Partner Chains smart contracts."
license = "Apache-2.0"

[dependencies]
log = { workspace = true }
sidechain-domain = { workspace = true, features = ["std"] }

cardano-serialization-lib = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
hex-literal = { workspace = true }
pretty_assertions = { workspace = true }
