[package]
name = "sidechain-block-search"
version = "1.7.0"
license = "Apache-2.0"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lints]
workspace = true

[dependencies]
parity-scale-codec = { workspace = true, features = ['std'] }
scale-info = { workspace = true, features = ['std'] }
serde = { workspace = true, features = ['std'] }

sp-core = { workspace = true, features = ['std'] }
sp-runtime = { workspace = true, features = ['std'] }
sp-api = { workspace = true, features = ['std'] }
sp-blockchain = { workspace = true }

sp-sidechain = { workspace = true, features = ['std'] , version = "1.7.0" }
sidechain-domain = { workspace = true, features = ['std'] , version = "1.7.0" }
hex = { workspace = true, features = ['std'] }

[dev-dependencies]
proptest = { workspace = true }
hex-literal = { workspace = true }
sp-consensus-aura = { workspace = true, features = ['std'] }
sp-consensus-slots = { workspace = true, features = ['std'] }
