[package]
name = "ogmios-client"
version = "1.2.0"
edition = "2021"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
hex = { workspace = true }
jsonrpsee = { workspace = true, optional = true, features = [
    "client-core",
    "http-client",
    "macros",
] }
serde = { workspace = true }
serde_json = { workspace = true, features = ["raw_value"] }
thiserror = { workspace = true }
time = { workspace = true, features = ["std", "serde", "parsing"] }

[dev-dependencies]
anyhow = { workspace = true }
tokio = { workspace = true }

[features]
default = ["jsonrpsee-client"]
jsonrpsee-client = ["jsonrpsee"]
