[package]
name = "sp-session-validator-management-query"
version = "1.5.1"
edition = "2021"
license = "Apache-2.0"

[dependencies]
parity-scale-codec = { workspace = true }
scale-info = { workspace = true }
async-trait = { workspace = true }
serde = { workspace = true }
derive-new = { workspace = true }
serde_json = { workspace = true }
sp-core = { workspace = true }
sp-runtime = { workspace = true }
sp-api = { workspace = true }
sp-blockchain = { workspace = true }
sp-session-validator-management = { workspace = true, features = ["std"] }
sp-sidechain = { workspace = true, features = ["std"] }
sidechain-domain = { workspace = true, features = ["std"] }
sidechain-block-search = { workspace = true }
authority-selection-inherents = { workspace = true, features = ["std"] }
thiserror = { workspace = true }
plutus = { workspace = true }

[dev-dependencies]
sp-std = { workspace = true }
hex-literal = { workspace = true }
minicbor = { workspace = true }
plutus-datum-derive = { workspace = true }
tokio = { workspace = true }
