[package]
name = "partner-chains-cardano-offchain"
version = "1.5.0"
authors = ["IOG"]
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/input-output-hk/partner-chains"
description = "Partner Chains Smart Contracts Offchain code"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
anyhow = { workspace = true }
cardano-serialization-lib = { workspace = true }
cbor_event = { workspace = true }
partner-chains-plutus-data = { workspace = true }
fraction = { workspace = true }
hex = { workspace = true }
hex-literal = { workspace = true }
log = { workspace = true }
minicbor = { workspace = true }
ogmios-client = { workspace = true, features = ["jsonrpsee-client"] }
pallas-addresses = { workspace = true }
pallas-primitives = { workspace = true }
plutus = { workspace = true }
raw-scripts = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true, features = ["std"] }
secp256k1 = { workspace = true, features = ["std"] }
sidechain-domain = { workspace = true, features = ["std"] }
uplc = { workspace = true }
tokio = { workspace = true }
tokio-retry = { workspace = true }

[dev-dependencies]
env_logger = { workspace = true }
fraction = { workspace = true, features = [
	"with-decimal",
	"with-serde-support",
] }
proptest = { workspace = true }
time = { workspace = true, features = ["std", "serde", "parsing"] }
pretty_assertions = { workspace = true }
testcontainers = { workspace = true }
