[package]
name = "pallet-block-producer-metadata-rpc"
version = "1.7.0"
license = "Apache-2.0"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
parity-scale-codec = { workspace = true, features = ['std'] }
scale-info = { workspace = true, features = ['std'] }
jsonrpsee = { workspace = true }
serde = { workspace = true, features = ['std'] }
sp-core = { workspace = true, features = ['std'] }
sp-runtime = { workspace = true, features = ['std'] }
sp-api = { workspace = true, features = ['std'] }
sp-blockchain = { workspace = true }
sp-block-producer-metadata = { workspace = true, features = ['std'] , version = "1.7.0" }
sidechain-domain = { workspace = true, features = ['std'] , version = "1.7.0" }
serde_json = { workspace = true, features = ['std'] }
derive-new = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }

[features]
default = []
mock = []
