name: Publish Documentation

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      rustdoc:
        description: "Build and publish the rustdoc"
        default: false
        type: boolean

env:
  SSH_AUTH_SOCK: /tmp/ssh_agent.sock

jobs:
  deploy-rustdoc:
    if: github.event_name != 'workflow_dispatch' || inputs.rustdoc
    name: Deploy Rust Docs
    runs-on: ubuntu-latest

    steps:
      - name: Install tooling
        run: |
          sudo apt-get install -y protobuf-compiler
          protoc --version

      - name: Checkout repository
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Add SSH key to read Substrate Repo
        run: |
          mkdir ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh-agent -a "$SSH_AUTH_SOCK" > /dev/null
          ssh-add - <<< "${{ secrets.SUBSTRATE_REPO_SSH_KEY }}"

      # With rustup's nice new toml format, we just need to run rustup show to install the toolchain
      # https://github.com/actions-rs/toolchain/issues/126#issuecomment-782989659
      - name: Rust versions
        run: rustup show

      - name: Rust cache
        uses: Swatinem/rust-cache@e207df5d269b42b69c8bc5101da26f7d31feddb4 # v2.6.2

      - name: Build rustdocs
        run: SKIP_WASM_BUILD=1 cargo doc --all --no-deps

      - name: Make index.html
        run: echo "<meta http-equiv=refresh content=0;url=node_template/index.html>" > ./target/doc/index.html

      - name: Deploy documentation
        if: github.ref_name == 'master'
        uses: peaceiris/actions-gh-pages@373f7f263a76c20808c831209c920827a82a2847 # v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./target/doc
